### ISSUE TITLE
when use dist_train.sh 

### ISSUE THREAD

**Issue by luoyinTT** [open-mmlab/mmediting#354] opened 2021-06-02 14:00 UTC
when i use **tools/dist_train.sh** to trian basicvsr, i meet:

ValueError: You may use too small dataset and our distributed sampler cannot pad your dataset correctly. We highly recommend you to use fewer GPUs to finish your work

my command is :
sh ./tools/dist_train.sh configs/restorers/basicvsr/basicvsr_vimeo90k_bi.py 2

but when i use tools/train.py (just use 1 GPU),there's no error

can anybody tell me how to solve this?

**Comment by ckkelvinchan** [comment] 2021-06-02 14:09
How many clips do you have for validation? 

This error is raised usually when the number of GPUs > number of test data (which is the number of video clips in this case).

**Comment by ckkelvinchan** [comment] 2021-06-02 14:11
If you encounter an error when using 2 GPUs but not 1, it's probably that you have training/validation data <=2 but >1

**Comment by ckkelvinchan** [comment] 2021-06-02 14:26
I have tried on my side and there is no error. 

And when there is no video clip inside the specified paths for validation, this error appears. You may need to check for the correctness of the paths.

**Comment by luoyinTT** [comment] 2021-06-02 14:47
@ckkelvinchan i meet this error now:


RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).

**Comment by ckkelvinchan** [comment] 2021-06-02 14:51
Did you use the newest version of the code? This issue should have been fixed in #290. Specifically, did you see 

`find_unused_parameters = True` in `basicvsr_vimeo90k_bi.py`?

**Comment by luoyinTT** [comment] 2021-06-03 09:47
@ckkelvinchan 
when test in training :

RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases yet.


what's this mean

**Comment by ckkelvinchan** [comment] 2021-06-03 09:57
Could you share with me your `mmedit/models/restorers/basicvsr.py`? I suspect that you may not be using the latest version. Please use the latest version of codes, or change `configs/restorers/basicsr/basicvsr_vimeo90k_bi.py` and `mmedit/models/restorers/basicvsr.py` according to #290. 

If the error persists, please provide us with more details to reproduce the errors.

**Comment by ckkelvinchan** [comment] 2021-07-12 02:35
Closing due to inactivity, please reopen if there are any further problems.

**Closed by ckkelvinchan** 2021-07-12 02:35 UTC
